name: cicd workflow

on: trigger

jobs:
  build and push to docker hub:
    name: build and push to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'main'
          owner: 'chedipfe'
          repository: 'angular'

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test